packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - prisma
  - sharp
  - unrs-resolver
