version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: joodang-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joodang
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d joodang"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  pg_data: